// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface/interface.go

// Package mockgen is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	tgbotapi "gopkg.in/telegram-bot-api.v4"
)

// MockTelegramMock is a mock of TelegramMock interface.
type MockTelegramMock struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramMockMockRecorder
}

// MockTelegramMockMockRecorder is the mock recorder for MockTelegramMock.
type MockTelegramMockMockRecorder struct {
	mock *MockTelegramMock
}

// NewMockTelegramMock creates a new mock instance.
func NewMockTelegramMock(ctrl *gomock.Controller) *MockTelegramMock {
	mock := &MockTelegramMock{ctrl: ctrl}
	mock.recorder = &MockTelegramMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramMock) EXPECT() *MockTelegramMockMockRecorder {
	return m.recorder
}

// NewBotAPI mocks base method.
func (m *MockTelegramMock) NewBotAPI(token string) (*tgbotapi.BotAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBotAPI", token)
	ret0, _ := ret[0].(*tgbotapi.BotAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewBotAPI indicates an expected call of NewBotAPI.
func (mr *MockTelegramMockMockRecorder) NewBotAPI(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBotAPI", reflect.TypeOf((*MockTelegramMock)(nil).NewBotAPI), token)
}

// NewMessage mocks base method.
func (m *MockTelegramMock) NewMessage(chatID int64, text string) tgbotapi.MessageConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMessage", chatID, text)
	ret0, _ := ret[0].(tgbotapi.MessageConfig)
	return ret0
}

// NewMessage indicates an expected call of NewMessage.
func (mr *MockTelegramMockMockRecorder) NewMessage(chatID, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMessage", reflect.TypeOf((*MockTelegramMock)(nil).NewMessage), chatID, text)
}

// Send mocks base method.
func (m *MockTelegramMock) Send(arg0 tgbotapi.Chattable) (tgbotapi.MessageConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(tgbotapi.MessageConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockTelegramMockMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTelegramMock)(nil).Send), arg0)
}
